#!/bin/bash

# EC2 Setup Script for Open Mandi Backend

set -e # Exit on error

echo "🚀 Starting Open Mandi EC2 Setup..."

# 1. Update and Install System Dependencies
echo "📦 Installing system dependencies..."
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g pnpm pm2

# 2. Install MongoDB (Community Edition)
# NOTE: Adjust depending on Ubuntu version. Assuming Ubuntu 22.04 or 20.04 commonly used on EC2.
if ! command -v mongod &> /dev/null
then
    echo "🍃 Installing MongoDB..."
    sudo apt-get install -y gnupg curl
    curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
       sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
       --dearmor
    
    # Check Ubuntu version
    UBUNTU_CODENAME=$(lsb_release -sc)
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu $UBUNTU_CODENAME/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
    
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    
    # Start MongoDB
    sudo systemctl start mongod
    sudo systemctl enable mongod
else
    echo "✅ MongoDB already installed."
fi

# 3. Setup Project
echo "🏗️ Setting up project..."
cd "$(dirname "$0")"

# Copy env.ec2 to .env if not exists
if [ ! -f .env ]; then
    echo "📝 Copying env.ec2 to .env..."
    cp env.ec2 .env
    echo "⚠️  IMPORTANT: Please edit .env and set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET now!"
else
    echo "ℹ️  .env already exists, skipping copy."
fi

echo "📦 Installing Node dependencies..."
pnpm install

echo "🔨 Building project..."
pnpm build

# 4. Start Server with PM2
echo "🚀 Starting server with PM2..."
pm2 start dist/server.js --name "open-mandi-backend" || pm2 restart "open-mandi-backend"
pm2 save
pm2 startup | tail -n 1 > startup_script.sh # Generate startup script but don't auto-run it, usually requires sudo
echo "ℹ️  Run the command generated by 'pm2 startup' to ensure persistence across reboots."

echo "✅ Setup Complete!"
echo "---------------------------------------------------"
echo "🔍 Verification Steps:"
echo "1. Edit .env and set Google credentials."
echo "2. Restart the app: pm2 restart open-mandi-backend"
echo "3. Check logs: pm2 logs open-mandi-backend"
echo "4. Test health: curl http://localhost:8000/health"
echo "---------------------------------------------------"
